"""initial migration

Revision ID: b48a436cc7de
Revises: None
Create Date: 2016-07-30 21:32:09.626455

"""

# revision identifiers, used by Alembic.
revision = 'b48a436cc7de'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info_subaccount', sa.Column('apikey', sa.String(length=34), nullable=False))
    op.add_column('info_subaccount', sa.Column('apisecret', sa.String(length=34), nullable=False))
    op.drop_column('info_subaccount', 'secret')
    op.drop_column('info_subaccount', 'key')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info_subaccount', sa.Column('key', sa.VARCHAR(length=34), nullable=False))
    op.add_column('info_subaccount', sa.Column('secret', sa.VARCHAR(length=34), nullable=False))
    op.drop_column('info_subaccount', 'apisecret')
    op.drop_column('info_subaccount', 'apikey')
    ### end Alembic commands ###
